spring:
  application:
    name: NulNLP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nul_nlp
    username: root
    password: sty@20030209
  data:
    redis:
      host: localhost
      port: 6379