spring:
  application:
    name: NulNLP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/nul_nlp
    # url: jdbc:mysql://localhost:3306/nul_nlp
    username: root
    password: sty@20030209
  data:
    # redis:
    #   host: redis
    #   port: 6379
    mongodb:
      host: mongodb
      # host: localhost
      port: 27017
      database: nul_nlp